import Link from "next/link";
import type { PublishedLocale } from "@/i18n/config";
import type { Messages } from "@/i18n/messages";
import { getLocalizedStoneName, type StoneCollectionEntry } from "@/content/v2-stones";
import { Container } from "./Container";

export function StoneCollection({ locale, stones, messages }: Readonly<{ locale: PublishedLocale; stones: readonly StoneCollectionEntry[]; messages: Messages["stonesExperience"]["collection"] }>) {
  return <main><Container className="py-12 md:py-20"><div className="max-w-[var(--container-reading)] border-s-2 border-[color:var(--color-foundation-accent)] ps-5"><p className="text-xs font-medium tracking-[0.14em] text-[color:var(--color-foundation-muted)]">{messages.label}</p><h1 className="mt-4 font-[family-name:var(--font-display)] text-[length:var(--text-title)] text-[color:var(--color-foundation-ink)]">{messages.title}</h1><p className="mt-5 text-base leading-7 text-[color:var(--color-foundation-muted)]">{messages.description}</p></div><div className="mt-12 border-t border-[color:var(--color-foundation-border)]"><p className="py-4 text-xs tracking-[0.1em] text-[color:var(--color-foundation-muted)]">{messages.pendingPortfolio}</p>{stones.map((stone, index) => <article key={stone.id} className="grid border-t border-[color:var(--color-foundation-border)] lg:grid-cols-[minmax(0,1.5fr)_minmax(18rem,1fr)]"><div className="flex min-h-72 items-end border-b border-[color:var(--color-foundation-border)] bg-[color:var(--color-foundation-surface)] p-6 lg:min-h-[30rem] lg:border-b-0 lg:border-e"><p className="max-w-xs text-sm leading-6 text-[color:var(--color-foundation-muted)]">{messages.mediaPending}</p></div><div className="flex flex-col justify-between p-6 md:p-10"><div><p className="text-xs tracking-[0.12em] text-[color:var(--color-foundation-muted)]">0{index + 1}</p><h2 className="mt-5 font-[family-name:var(--font-display)] text-4xl text-[color:var(--color-foundation-ink)]">{getLocalizedStoneName(stone.name, locale)}</h2><p className="mt-5 text-sm leading-6 text-[color:var(--color-foundation-muted)]">{messages.detailsPending}</p></div><Link href={`/${locale}/stones/${stone.slug}`} className="mt-10 inline-flex min-h-11 w-fit items-center border-b border-[color:var(--color-foundation-ink)] text-xs font-medium tracking-[0.1em] text-[color:var(--color-foundation-ink)] hover:text-[color:var(--color-foundation-accent)]">{messages.detailsLink}</Link></div></article>)}</div></Container></main>;
}
